### ISSUE TITLE
Extend HTTP api to allow terminating a session with an HTTP DELETE

### ISSUE THREAD

**Issue by murillo128** [murillo128/webrtc-http-ingest-protocol#2]
In order to provide a more rest-like behavior to the protocol, an alternative method to terminate current ingestion session could be added.

Supporting DTLS disconnection would still need to be supported by the server, but it could also be possible to end it with an HTTP  DELETE request to the session resource URL.

In order to allow stateless load balancing this URL could be different than the original HTTP POST URL. 

In order to support that, the HTTP POST will return a  201 Created response with a Location header indicating the URL of the streaming session resource.

So, an encoder could choose to do an HTTP DELETE to the streaming resource URL in order to terminate the current streaming session. Note that this DELETE operation will not delete any recording or generated content, just terminate the streaming service on the server side.

While this could add a redundant way of terminating a session (the DTLS shutdown would still be required to be supported), it allows to avoid issues with DTLS alert retransmission.

It will also open the door for extending the protocol by allowing more operations to be performed against this streaming session resource URL.

cc/ @lminiero @steely-glint

**Comment by notedit** [comment]
the resource URL maybe like  "webrtc://domain/app/stream"

**Comment by murillo128** [comment]
I don't like the idea of adding a new url schema if the transport protocol is http.

**Comment by steely-glint** [comment]
I'd like to keep webrtc:// for the No Offer/Answer variant. Negotiation isn't always needed. Especially when setting up data-channel only sessions.

**Comment by murillo128** [comment]
I agrre, for me a new schema for a url makes sense if the transport is new
or if we had uris for identifying peers somehow.

**Comment by osctt** [comment]
`hotel`
