### ISSUE TITLE
Add DTLS setup constraint

### ISSUE THREAD

**Issue by steely-glint** [murillo128/webrtc-http-ingest-protocol#6]
In addition to requireing  BUNDLE and rtcp-mux, we could also require the the answer 
contains a=setup passive 
i.e. that the consumer is always a DTLS server.

This simplifies the producer code.

**Comment by steely-glint** [comment]
I don't think it is legal to send setup=active in a webRTC offer 
https://tools.ietf.org/html/rfc5763#section-5

**Comment by murillo128** [comment]
I agree, then. Will make the changes tonight.
